name: .\envs
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - asn1crypto=1.3.0
  - astor=0.8.0
  - blas=1.0
  - blinker=1.4
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - cryptography=2.8
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - freetype=2.9.1
  - gast=0.2.2
  - google-auth=1.13.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.27.2
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=64.2
  - idna=2.9
  - intel-openmp=2020.0
  - jpeg=9c
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopencv=4.2.0
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libtiff=4.1.0
  - libwebp=1.0.2
  - markdown=3.1.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - opencv=4.2.0
  - openssl=1.1.1
  - opt_einsum=3.1.0
  - pandas=1.0.3
  - pip=20.0.2
  - protobuf=3.11.4
  - py-opencv=4.2.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyreadline=2.1
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2019.3
  - qt=5.12.5
  - requests=2.23.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - scipy=1.4.1
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tensorboard=2.1.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - tensorflow-gpu=2.1.0
  - termcolor=1.1.0
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - werkzeug=0.14.1
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
      - astroid==2.3.3
      - colorama==0.4.3
      - cycler==0.10.0
      - imutils==0.5.3
      - isort==4.3.21
      - joblib==0.14.1
      - keras==2.3.1
      - kiwisolver==1.2.0
      - lazy-object-proxy==1.4.3
      - matplotlib==3.2.1
      - mccabe==0.6.1
      - pylint==2.4.4
      - pyparsing==2.4.7
      - pyyaml==5.3.1
      - scikit-learn==0.22.2.post1
      - seaborn==0.10.0
      - sklearn==0.0
      - typed-ast==1.4.1
      - wrapt==1.11.2
